# cargo install --locked --git https://github.com/estin/simple-completion-language-server.git
# simple-completion-language-server fetch-external-snippets
[[sources]]
name = "friendly-snippets"
git = "https://github.com/rafamadriz/friendly-snippets.git"

[[sources.paths]]
scope = ["go"]
path = "snippets/go.json"

[[sources.paths]]
scope = ["rust"]
path = "snippets/rust/rust.json"

[[sources.paths]]
scope = ["rust"]
path = "snippets/rust/rustdoc.json"

[[sources.paths]]
scope = ["ruby"]
path = "snippets/ruby/ruby.json"

[[sources.paths]]
scope = ["ruby"]
path = "snippets/ruby/rspec.json"

[[sources.paths]]
scope = ["ruby"]
path = "snippets/ruby/rdoc.json"

[[sources.paths]]
scope = ["sql"]
path = "snippets/sql.json"
